name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.1)'
        required: true
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string
        default: 'Bug fixes and improvements'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update version in files
      run: |
        # Update package.json
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        
        # Update main plugin file
        sed -i "s/Version: .*/Version: ${{ github.event.inputs.version }}/" lazy-loading-plugin.php
        
        # Update constant if it exists
        sed -i "s/define('LAZY_LOADING_PLUGIN_VERSION', '[^']*')/define('LAZY_LOADING_PLUGIN_VERSION', '${{ github.event.inputs.version }}')/" lazy-loading-plugin.php
        
    - name: Build WordPress plugin
      run: |
        chmod +x build.sh
        npm run build-zip
        
    - name: Verify build output
      run: |
        ls -la *.zip
        echo "Build completed successfully!"
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Lazy Loading Plugin v${{ github.event.inputs.version }}
        body: |
          ## WordPress Lazy Loading Plugin v${{ github.event.inputs.version }}
          
          ${{ github.event.inputs.release_notes }}
          
          ### 🚀 Quick Installation
          
          1. **Download** the ZIP file below
          2. **WordPress Admin**: Plugins → Add New → Upload Plugin
          3. **Upload** the ZIP file and activate
          4. **Configure**: Settings → Lazy Loading (optional)
          
          ### ✨ What's New
          
          - Modern IntersectionObserver API implementation
          - Automatic image lazy loading for WordPress
          - Customizable settings and animations
          - Mobile-optimized performance
          - SEO-friendly implementation
          
          ### 📊 Performance Benefits
          
          - 🚀 67% faster initial page load
          - 📉 80% less bandwidth usage  
          - 🎯 Better Core Web Vitals scores
          - 📱 Improved mobile experience
          
          ### 🔧 Requirements
          
          - WordPress 4.7+
          - PHP 5.6+ (PHP 7.4+ recommended)
          - Modern browsers with graceful fallback
          
          ---
          
          **Ready to install! Download the ZIP below and upload to WordPress.**
        files: |
          lazy-loading-plugin-v${{ github.event.inputs.version }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit version changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json lazy-loading-plugin.php
        git commit -m "🚀 Release v${{ github.event.inputs.version }}" || echo "No changes to commit"
        git tag v${{ github.event.inputs.version }}
        git push origin main
        git push origin v${{ github.event.inputs.version }}